### ISSUE TITLE
Not working in UIBarButton ?

### ISSUE THREAD

**Issue by TayfunAslan** [docterd/VYPlayIndicator#1]
Hello,

I use your lib' in my project, i want add this play indicator in UIBarButton with init custom view as UIButton. this not working... how could I do?

Thanks

**Comment by obrhoff** [comment]
Haven't checked yet. Keep in mind, that CALayers are not affected by Autolayout. You need to update the Frame in layoutSublayersOfLayer / layoutSubviews.

**Comment by TayfunAslan** [comment]
Ok, I have solved my problem to create a file subclassed UIButton and I override layoutSublayersOfLayer / layoutSubviews methods.

Thanks.

**Comment by TayfunAslan** [comment]
Thanks.
