### ISSUE TITLE
UITableView delete mode 

### ISSUE THREAD

**Issue by praveenkumar56060** [docterd/VYPlayIndicator#4]
Hello Team,

Its behaving weird when delete mode appears. You can refer below screenshot.

![thumb_img_0187_1025](https://cloud.githubusercontent.com/assets/9106340/13493772/2ff9ee40-e166-11e5-9ce2-f853f57a0522.jpg)

**Comment by praveenkumar56060** [comment]
You can check with your [sample](https://github.com/docterd/VYPlayIndicator/files/156821/VYPlayIndicator-master.zip) itself which i've modified for you. Just try it out. Especially, try it out with iOS7

**Comment by obrhoff** [comment]
Hey. I can't reproduce the problem. Do you mean the graphical glitches or did you obscure your screenshot?

**Comment by praveenkumar56060** [comment]
No i am saying about the graphical glitches on `UITableView` when it comes to edit mode. You can check it by [this example](https://github.com/docterd/VYPlayIndicator/files/156821/VYPlayIndicator-master.zip)

**Comment by obrhoff** [comment]
Hmm weird. I can't reproduce it :-/ 

![simulator screen shot 11 mar 2016 11 45 58](https://cloud.githubusercontent.com/assets/199578/13700068/e46671e6-e77e-11e5-9cb1-10acabb33e05.png)
![simulator screen shot 11 mar 2016 11 45 59](https://cloud.githubusercontent.com/assets/199578/13700069/e4695ece-e77e-11e5-8779-51b5775b6379.png)

**Comment by praveenkumar56060** [comment]
Delete some record and scroll your tableview, you'll able to see that glitch.
